### ISSUE TITLE
In Scoping, add conditions

### ISSUE THREAD

**Issue by AmeliaNestler** [NorthwestGreenChemistry/PrISM#78]
Review for conditions and add.At least one in feedstock - biobased should prompt the other question.

**Comment by AmeliaNestler** [comment]
And add other to ecolabel question that is on a conditional.

**Comment by AmeliaNestler** [comment]
Tried this edit today, but doesn't seem to be doing anything. Not getting any errors (yay) but not seeing the conditional work. Edits were made in \PrISM\app\assets\quiz\guiding_questions1_rules.json following the EDITING_QUESTIONS.md file. I also compared to conditionals in step 2 and it seems to be done correctly.

**Comment by AmeliaNestler** [comment]
@sjgllghr pointed out that I need to reference the section as well, so added "feedstock." in front of each question like I see it in other files. And now it doesn't show that question when nothing is checked (YAY!) but it also doesn't appear when I check "Bio-based". So, progress of a sort. What else am I missing?

**Comment by sjgllghr** [comment]
I'm guessing it's because the question you're applying the conditional to has a period at the end. It's mentioned in the guide, but basically right now periods don't work as punctuation for questions that have conditional rules. (Since "." is used to tell what sub-section a question is from, if you use a period in your question it'll think whats before the period is a subsection and not be able to find it)

https://github.com/NorthwestGreenChemistry/PrISM/blob/53cc6022d0a352b6aa2910f676d2a01610ec1936/app/assets/quiz/guiding_questions1_rules.json#L4

**Comment by AmeliaNestler** [comment]
Woohooo, it works now! Remove the '.' didn't fix it completely; that got the conditional question to disappear but it wouldn't reappear. Removed the dash in bio-based (changed to biobased), and now it works!
